let questionsList = ['I always tell only the truth.',
	                 'My affairs are worse than others.',
	                 'I will not begin to tell everything about myself to even a loved one.',
	                 'I am a completely healthy person.',
	                 'I often have a sad mood.',
	                 'I do not care if the people around me like me.',
	                 'I strive to succeed in life.',
	                 'My character is too soft.',
	                 'I strive to defend my opinion at all costs.',
	                 'Often I worry about nothing.']